### ISSUE TITLE
is this still work?

### ISSUE THREAD

**Issue by kwangsung-ha** [jupe76/bmwcdapi#1]
same with title

**Comment by wywywywy** [comment]
The API endpoint `https://customer.bmwgroup.com/gcdm/oauth/authenticate` doesn't seem to exist any more

**Comment by jupe76** [comment]
I've changed the authentication method recently , it is reported to work in the States now.
You still have to adjust  SERVER_URL from 'b2vapi.bmwgroup.com' to 'b2vapi.bmwgroup.us' in bmwcdapi.py
