### ISSUE TITLE
Problem with Authentication

### ISSUE THREAD

**Issue by xSaleGG** [jupe76/bmwcdapi#10]
Hello,

Got a problem when i'm running the script.
It only shows the message: ...running bmwcdapi.py could not authenticate, user or password wrong?

The passwort is correct and i can login at https://www.bmw-connecteddrive.de/

Is there anything i have to change in the script to access the german API?

**Comment by bak3rmak3r** [comment]
They did change the API Servers and token request procedure. Have a look at https://github.com/bimmerconnected/bimmer_connected/commit/ffaf409c7f93e2bac9ee8167f29c438cf997d67d#diff-e31c3d16927bd28d987f9433ff5f505a.

I could not figure out hwo to get it working again. But as jupe76 seems to not work on that script it would be great if we would share our results.

cheers

**Comment by Jagohu** [comment]
I've tried and it seems like I succeeded. My OpenHAB items have updated after running the script I have slightly modified. (based on [https://github.com/bimmerconnected/bimmer_connected/releases/tag/0.7.0](url) and [https://github.com/bimmerconnected/bimmer_connected/commit/ffaf409c7f93e2bac9ee8167f29c438cf997d67d#diff-e31c3d16927bd28d987f9433ff5f505a](url) )
Enjoy!
[bmwcdapi.zip](https://github.com/jupe76/bmwcdapi/files/4236399/bmwcdapi.zip)

**Comment by bak3rmak3r** [comment]
Thank You a lot. I do get a new token but values are not yet updated. But there is no error or something.

**Comment by Jagohu** [comment]
It seems like after you get a new token, you can run the old .py again and it works... Odd, I'll try to have a look at it again, maybe it's only the token request procedure which has to be adjusted. Sorry, 
For me it did update after running it. Then indeed it didn't. So now I ran the old script, and voila' - it updated. Try this, maybe it works...

I'm not a Python wiz, but will try to figure it out. If there's anyone out there who has a more in-depth knowledge, please feel free to merge the codes.

**Comment by bak3rmak3r** [comment]
Ok, great. Thank you for checking it as i am also really not into python.

**Comment by leiweke** [comment]
yes can confirm that the new token with the fixed version arrived but need to get back to the original py version to get the values updated.

**Comment by Jagohu** [comment]
Cool, that's at least one step ahead :) I'm glad it works even if it's not perfec. I'll try to figure out something.

**Comment by jupe76** [comment]
I've pushed a fix to the repo based on the bimmer_connected lib.
Authentication should work again now, at least for "the rest of the world"

**Comment by bak3rmak3r** [comment]
That is working smoothly. Thank You for updating!

**Comment by Jagohu** [comment]
@jupe76 : Thanks a lot!
