### ISSUE TITLE
Add LifeTimeList ?!

### ISSUE THREAD

**Issue by Firebird231** [jupe76/bmwcdapi#11]
Hi, some quite useful information are stored here:
lifeTimeList []
scoreList [{'attrUnit': 'KWH_PER_100KM', 'attrName': 'AVERAGE_ELECTRIC_CONSUMPTION', 'lifeTime': 14.9, 'minValue': 0.0, 'maxValue': 40.0}, {'attrUnit': 'KWH_PER_100KM', 'attrName': 'AVERAGE_RECUPERATED_ENERGY_PER_100_KM', 'lifeTime': 4.9, 'minValue': 0.0, 'maxValue': 20.0}, {'attrUnit': 'KM', 'attrName': 'CUMULATED_ELECTRIC_DRIVEN_DISTANCE', 'lifeTime': 64.0, 'minValue': 0.0, 'maxValue': 65.0}, {'attrUnit': 'KM', 'attrName': 'LONGEST_DISTANCE_WITHOUT_CHARGING', 'lifeTime': 24.0, 'minValue': 0.0, 'maxValue': 170.0}]
execStatusCode=0

Could you explain how to add them in bmwcdapi.py or integrate them by yourself?

BTW: The LASTTRIP_DELTA_KM out of lastTripList was deactived? Why? I added it again - worked fine

**Comment by odelma** [comment]
Nice, how did you get this response from ConnectedDrive? I'd like to add the lifetime values as well... 😄

**Comment by Firebird231** [comment]
Just run the Script in karaf Console..

Von meinem iPhone gesendet
