### ISSUE TITLE
BMW ConnectedDrive in the US is not able to work with the script

### ISSUE THREAD

**Issue by dikodahan** [jupe76/bmwcdapi#5]
I am based in the US and using https://connecteddrive.bmwusa.com where I can login and see my car. As a test I figured I would look for a global ConnectedDrive site and found this one: https://www.bmw-connecteddrive.my

After I completed the register process I am no longer getting the UN & PW error. However, when I try to add my vehicle there it says it cannot validate this vehicle. So obviously this plugin was written for EU based cars but has issues with the US ConnectedDrive version.

**Comment by jupe76** [comment]
I've changed the authentication method recently , it is reported to work in the States now.
You still have to adjust  SERVER_URL from 'b2vapi.bmwgroup.com' to 'b2vapi.bmwgroup.us' in bmwcdapi.py
